#ifndef __KL2EDK_AUTOGEN_AtArray__
#define __KL2EDK_AUTOGEN_AtArray__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtArray.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtArray'
// Defined at ai_params.kl:19:1

struct AtArray
{
  typedef AtArray &Result;
  typedef AtArray const &INParam;
  typedef AtArray &IOParam;
  typedef AtArray &OUTParam;
  
  Data atParamValue;
};

inline void Traits<AtArray>::ConstructEmpty( AtArray &val )
{
  Traits< Data >::ConstructEmpty( val.atParamValue );
}
inline void Traits<AtArray>::ConstructCopy( AtArray &lhs, AtArray const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.atParamValue, rhs.atParamValue );
}
inline void Traits<AtArray>::AssignCopy( AtArray &lhs, AtArray const &rhs )
{
  Traits< Data >::AssignCopy( lhs.atParamValue, rhs.atParamValue );
}
inline void Traits<AtArray>::Destruct( AtArray &val )
{
  Traits< Data >::Destruct( val.atParamValue );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtArray__
