#ifndef __KL2EDK_AUTOGEN_AtMetaDataIterator__
#define __KL2EDK_AUTOGEN_AtMetaDataIterator__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtMetaDataIterator.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtMetaDataIterator'
// Defined at ai_node_entry.kl:20:1

struct AtMetaDataIterator
{
  typedef AtMetaDataIterator &Result;
  typedef AtMetaDataIterator const &INParam;
  typedef AtMetaDataIterator &IOParam;
  typedef AtMetaDataIterator &OUTParam;
  
  Data internal;
};

inline void Traits<AtMetaDataIterator>::ConstructEmpty( AtMetaDataIterator &val )
{
  Traits< Data >::ConstructEmpty( val.internal );
}
inline void Traits<AtMetaDataIterator>::ConstructCopy( AtMetaDataIterator &lhs, AtMetaDataIterator const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtMetaDataIterator>::AssignCopy( AtMetaDataIterator &lhs, AtMetaDataIterator const &rhs )
{
  Traits< Data >::AssignCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtMetaDataIterator>::Destruct( AtMetaDataIterator &val )
{
  Traits< Data >::Destruct( val.internal );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtMetaDataIterator__
