#ifndef __KL2EDK_AUTOGEN_AtParamEntry__
#define __KL2EDK_AUTOGEN_AtParamEntry__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtParamEntry.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtParamEntry'
// Defined at ai_params.kl:30:1

struct AtParamEntry
{
  typedef AtParamEntry &Result;
  typedef AtParamEntry const &INParam;
  typedef AtParamEntry &IOParam;
  typedef AtParamEntry &OUTParam;
  
  Data handle;
};

inline void Traits<AtParamEntry>::ConstructEmpty( AtParamEntry &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<AtParamEntry>::ConstructCopy( AtParamEntry &lhs, AtParamEntry const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtParamEntry>::AssignCopy( AtParamEntry &lhs, AtParamEntry const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtParamEntry>::Destruct( AtParamEntry &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtParamEntry__
