#ifndef __KL2EDK_AUTOGEN_AtParamValue__
#define __KL2EDK_AUTOGEN_AtParamValue__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtParamValue.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtParamValue'
// Defined at ai_params.kl:8:1

struct AtParamValue
{
  typedef AtParamValue &Result;
  typedef AtParamValue const &INParam;
  typedef AtParamValue &IOParam;
  typedef AtParamValue &OUTParam;
  
  Data atParamValue;
};

inline void Traits<AtParamValue>::ConstructEmpty( AtParamValue &val )
{
  Traits< Data >::ConstructEmpty( val.atParamValue );
}
inline void Traits<AtParamValue>::ConstructCopy( AtParamValue &lhs, AtParamValue const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.atParamValue, rhs.atParamValue );
}
inline void Traits<AtParamValue>::AssignCopy( AtParamValue &lhs, AtParamValue const &rhs )
{
  Traits< Data >::AssignCopy( lhs.atParamValue, rhs.atParamValue );
}
inline void Traits<AtParamValue>::Destruct( AtParamValue &val )
{
  Traits< Data >::Destruct( val.atParamValue );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtParamValue__
