#ifndef __KL2EDK_AUTOGEN_AtTextureHandle__
#define __KL2EDK_AUTOGEN_AtTextureHandle__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtTextureHandle.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtTextureHandle'
// Defined at ai_texture.kl:8:1

struct AtTextureHandle
{
  typedef AtTextureHandle &Result;
  typedef AtTextureHandle const &INParam;
  typedef AtTextureHandle &IOParam;
  typedef AtTextureHandle &OUTParam;
  
  Data handle;
};

inline void Traits<AtTextureHandle>::ConstructEmpty( AtTextureHandle &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<AtTextureHandle>::ConstructCopy( AtTextureHandle &lhs, AtTextureHandle const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtTextureHandle>::AssignCopy( AtTextureHandle &lhs, AtTextureHandle const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtTextureHandle>::Destruct( AtTextureHandle &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtTextureHandle__
