#ifndef __KL2EDK_AUTOGEN_AtUserParamEntry__
#define __KL2EDK_AUTOGEN_AtUserParamEntry__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtUserParamEntry.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtUserParamEntry'
// Defined at ai_params.kl:34:1

struct AtUserParamEntry
{
  typedef AtUserParamEntry &Result;
  typedef AtUserParamEntry const &INParam;
  typedef AtUserParamEntry &IOParam;
  typedef AtUserParamEntry &OUTParam;
  
  Data handle;
};

inline void Traits<AtUserParamEntry>::ConstructEmpty( AtUserParamEntry &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<AtUserParamEntry>::ConstructCopy( AtUserParamEntry &lhs, AtUserParamEntry const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtUserParamEntry>::AssignCopy( AtUserParamEntry &lhs, AtUserParamEntry const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtUserParamEntry>::Destruct( AtUserParamEntry &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtUserParamEntry__
