#ifndef __KL2EDK_AUTOGEN_AtAOVIterator__
#define __KL2EDK_AUTOGEN_AtAOVIterator__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtAOVIterator.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtAOVIterator'
// Defined at GenKL\\ai_universe.kl:16:1

struct AtAOVIterator
{
  typedef AtAOVIterator &Result;
  typedef AtAOVIterator const &INParam;
  typedef AtAOVIterator &IOParam;
  typedef AtAOVIterator &OUTParam;
  
  Data iterator;
};

inline void Traits<AtAOVIterator>::ConstructEmpty( AtAOVIterator &val )
{
  Traits< Data >::ConstructEmpty( val.iterator );
}
inline void Traits<AtAOVIterator>::ConstructCopy( AtAOVIterator &lhs, AtAOVIterator const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.iterator, rhs.iterator );
}
inline void Traits<AtAOVIterator>::AssignCopy( AtAOVIterator &lhs, AtAOVIterator const &rhs )
{
  Traits< Data >::AssignCopy( lhs.iterator, rhs.iterator );
}
inline void Traits<AtAOVIterator>::Destruct( AtAOVIterator &val )
{
  Traits< Data >::Destruct( val.iterator );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtAOVIterator__
