#ifndef __KL2EDK_AUTOGEN_AtNodeMethods__
#define __KL2EDK_AUTOGEN_AtNodeMethods__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtNodeMethods.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtNodeMethods'
// Defined at GenKL\\ai_node_entry.kl:12:1

struct AtNodeMethods
{
  typedef AtNodeMethods &Result;
  typedef AtNodeMethods const &INParam;
  typedef AtNodeMethods &IOParam;
  typedef AtNodeMethods &OUTParam;
  
  Data internal;
};

inline void Traits<AtNodeMethods>::ConstructEmpty( AtNodeMethods &val )
{
  Traits< Data >::ConstructEmpty( val.internal );
}
inline void Traits<AtNodeMethods>::ConstructCopy( AtNodeMethods &lhs, AtNodeMethods const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtNodeMethods>::AssignCopy( AtNodeMethods &lhs, AtNodeMethods const &rhs )
{
  Traits< Data >::AssignCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtNodeMethods>::Destruct( AtNodeMethods &val )
{
  Traits< Data >::Destruct( val.internal );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtNodeMethods__
