#ifndef __KL2EDK_AUTOGEN_AtParamIterator__
#define __KL2EDK_AUTOGEN_AtParamIterator__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtParamIterator.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtParamIterator'
// Defined at GenKL\\ai_node_entry.kl:16:1

struct AtParamIterator
{
  typedef AtParamIterator &Result;
  typedef AtParamIterator const &INParam;
  typedef AtParamIterator &IOParam;
  typedef AtParamIterator &OUTParam;
  
  Data internal;
};

inline void Traits<AtParamIterator>::ConstructEmpty( AtParamIterator &val )
{
  Traits< Data >::ConstructEmpty( val.internal );
}
inline void Traits<AtParamIterator>::ConstructCopy( AtParamIterator &lhs, AtParamIterator const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtParamIterator>::AssignCopy( AtParamIterator &lhs, AtParamIterator const &rhs )
{
  Traits< Data >::AssignCopy( lhs.internal, rhs.internal );
}
inline void Traits<AtParamIterator>::Destruct( AtParamIterator &val )
{
  Traits< Data >::Destruct( val.internal );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtParamIterator__
