#ifndef __KL2EDK_AUTOGEN_AtScrSample__
#define __KL2EDK_AUTOGEN_AtScrSample__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtScrSample.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtScrSample'
// Defined at GenKL\\ai_ray.kl:12:1

struct AtScrSample
{
  typedef AtScrSample &Result;
  typedef AtScrSample const &INParam;
  typedef AtScrSample &IOParam;
  typedef AtScrSample &OUTParam;
  
  Data handle;
};

inline void Traits<AtScrSample>::ConstructEmpty( AtScrSample &val )
{
  Traits< Data >::ConstructEmpty( val.handle );
}
inline void Traits<AtScrSample>::ConstructCopy( AtScrSample &lhs, AtScrSample const &rhs )
{
  Traits< Data >::ConstructCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtScrSample>::AssignCopy( AtScrSample &lhs, AtScrSample const &rhs )
{
  Traits< Data >::AssignCopy( lhs.handle, rhs.handle );
}
inline void Traits<AtScrSample>::Destruct( AtScrSample &val )
{
  Traits< Data >::Destruct( val.handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtScrSample__
