////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include "global_functions.h"

using namespace Fabric::EDK;


// Defined at ai_params.kl:77:1
FABRIC_EXT_EXPORT void _fe_AiParamGetName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::INParam pentry
)
{
}

// Defined at ai_params.kl:78:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiParamGetType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::INParam pentry
)
{
}

// Defined at ai_params.kl:79:1
FABRIC_EXT_EXPORT void _fe_AiParamGetDefault(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::INParam pentry
)
{
}

// Defined at ai_params.kl:80:1
FABRIC_EXT_EXPORT void _fe_AiParamGetEnum(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::INParam pentry
)
{
}

// Defined at ai_params.kl:81:1
FABRIC_EXT_EXPORT void _fe_AiParamGetTypeName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt8 >::INParam type
)
{
}

// Defined at ai_params.kl:82:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiParamGetTypeSize(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt8 >::INParam type
)
{
}

// Defined at ai_params.kl:88:1
FABRIC_EXT_EXPORT void _fe_AiUserParamGetName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::INParam upentry
)
{
}

// Defined at ai_params.kl:89:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiUserParamGetType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::INParam upentry
)
{
}

// Defined at ai_params.kl:90:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiUserParamGetArrayType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::INParam upentry
)
{
}

// Defined at ai_params.kl:91:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiUserParamGetCategory(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::INParam upentry
)
{
}

// Defined at ai_params.kl:92:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiUserParamGetIndex(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::INParam upentry
)
{
}

// Defined at ai_params.kl:93:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamByte(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt8 >::INParam pdefault
)
{
}

// Defined at ai_params.kl:94:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamInt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam pdefault
)
{
}

// Defined at ai_params.kl:95:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamUInt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam pdefault
)
{
}

// Defined at ai_params.kl:96:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamBool(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam pdefault
)
{
}

// Defined at ai_params.kl:97:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamFlt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam pdefault
)
{
}

// Defined at ai_params.kl:98:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamRGB(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam r,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam g,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam b
)
{
}

// Defined at ai_params.kl:99:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamRGBA(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam r,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam g,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam b,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam a
)
{
}

// Defined at ai_params.kl:100:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamVec(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam z
)
{
}

// Defined at ai_params.kl:101:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamPnt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam z
)
{
}

// Defined at ai_params.kl:102:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamPnt2(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y
)
{
}

// Defined at ai_params.kl:103:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamStr(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pdefault
)
{
}

// Defined at ai_params.kl:104:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamPtr(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam pdefault
)
{
}

// Defined at ai_params.kl:105:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamNode(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam pdefault
)
{
}

// Defined at ai_params.kl:106:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamArray(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::IOParam pdefault
)
{
}

// Defined at ai_params.kl:107:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamMtx(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::INParam matrix
)
{
}

// Defined at ai_params.kl:108:1
FABRIC_EXT_EXPORT void _fe_AiNodeParamEnum(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam varoffset,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam pname,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam pdefault,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::INParam enum_type
)
{
}

// Defined at ai_cameras.kl:47:1
FABRIC_EXT_EXPORT void _fe_AiCameraInitialize(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam data
)
{
}

// Defined at ai_cameras.kl:48:1
FABRIC_EXT_EXPORT void _fe_AiCameraUpdate(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam plane_distance
)
{
}

// Defined at ai_cameras.kl:49:1
FABRIC_EXT_EXPORT void _fe_AiCameraDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node
)
{
}

// Defined at ai_cameras.kl:50:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Data _fe_AiCameraGetLocalData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_dotass.kl:8:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiASSWrite(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam mask,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam open_procs,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam binary
)
{
}

// Defined at ai_dotass.kl:9:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiASSLoad(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam mask
)
{
}

// Defined at ai_enum.kl:8:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiEnumGetValue(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::INParam enum_type,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam string
)
{
}

// Defined at ai_enum.kl:9:1
FABRIC_EXT_EXPORT void _fe_AiEnumGetString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::INParam enum_type,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam index
)
{
}

// Defined at ai_license.kl:77:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiLicenseSetServer(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam host,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam port
)
{
}

// Defined at ai_license.kl:78:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiLicenseGetServer(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::IOParam host,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam port
)
{
}

// Defined at ai_license.kl:79:1
FABRIC_EXT_EXPORT void _fe_AiLicenseSetAttempts(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam attempts
)
{
}

// Defined at ai_license.kl:80:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 _fe_AiLicenseGetAttempts(
)
{
}

// Defined at ai_license.kl:81:1
FABRIC_EXT_EXPORT void _fe_AiLicenseSetAttemptDelay(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam msecs
)
{
}

// Defined at ai_license.kl:82:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 _fe_AiLicenseGetAttemptDelay(
)
{
}

// Defined at ai_license.kl:83:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiLicenseGetInfo(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtLicenseInfo >::IOParam licenses,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam n
)
{
}

// Defined at ai_metadata.kl:26:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetBool(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam value
)
{
}

// Defined at ai_metadata.kl:27:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetBoolAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam value
)
{
}

// Defined at ai_metadata.kl:28:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetInt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam value
)
{
}

// Defined at ai_metadata.kl:29:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam value
)
{
}

// Defined at ai_metadata.kl:30:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetFlt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam value
)
{
}

// Defined at ai_metadata.kl:31:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetFltAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam value
)
{
}

// Defined at ai_metadata.kl:32:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetRGB(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:33:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetRGBAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:34:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetVec(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:35:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetVecAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:36:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetPnt(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:37:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetPntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam value
)
{
}

// Defined at ai_metadata.kl:38:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetPnt2(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec2 >::INParam value
)
{
}

// Defined at ai_metadata.kl:39:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetPnt2AtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec2 >::INParam value
)
{
}

// Defined at ai_metadata.kl:40:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetStr(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam value
)
{
}

// Defined at ai_metadata.kl:41:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataSetStrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataStore >::IOParam mds,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam value
)
{
}

// Defined at ai_metadata.kl:55:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetBoolAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::IOParam value
)
{
}

// Defined at ai_metadata.kl:56:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:57:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetFltAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:58:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetRGBAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:59:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetVecAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:60:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetPntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:61:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetPnt2AtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec2 >::IOParam value
)
{
}

// Defined at ai_metadata.kl:62:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataGetStrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam entry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam value
)
{
}

// Defined at ai_metadata.kl:73:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataLoadFile(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename
)
{
}

// Defined at ai_msg.kl:37:1
FABRIC_EXT_EXPORT void _fe_AiMsgSetLogFileName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename
)
{
}

// Defined at ai_msg.kl:38:1
FABRIC_EXT_EXPORT void _fe_AiMsgSetLogFileFlags(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam flags
)
{
}

// Defined at ai_msg.kl:39:1
FABRIC_EXT_EXPORT void _fe_AiMsgSetConsoleFlags(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam flags
)
{
}

// Defined at ai_msg.kl:40:1
FABRIC_EXT_EXPORT void _fe_AiMsgSetMaxWarnings(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam max_warnings
)
{
}

// Defined at ai_msg.kl:41:1
FABRIC_EXT_EXPORT void _fe_AiMsgResetCallback(
)
{
}

// Defined at ai_msg.kl:42:1
FABRIC_EXT_EXPORT void _fe_AiMsgInfo(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam format
)
{
}

// Defined at ai_msg.kl:43:1
FABRIC_EXT_EXPORT void _fe_AiMsgDebug(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam format
)
{
}

// Defined at ai_msg.kl:44:1
FABRIC_EXT_EXPORT void _fe_AiMsgWarning(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam format
)
{
}

// Defined at ai_msg.kl:45:1
FABRIC_EXT_EXPORT void _fe_AiMsgError(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam format
)
{
}

// Defined at ai_msg.kl:46:1
FABRIC_EXT_EXPORT void _fe_AiMsgFatal(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam format
)
{
}

// Defined at ai_msg.kl:47:1
FABRIC_EXT_EXPORT void _fe_AiMsgTab(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam tabinc
)
{
}

// Defined at ai_msg.kl:48:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt64 _fe_AiMsgUtilGetUsedMemory(
)
{
}

// Defined at ai_msg.kl:49:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 _fe_AiMsgUtilGetElapsedTime(
)
{
}

// Defined at ai_node_entry.kl:52:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryLookUpAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
}

// Defined at ai_node_entry.kl:53:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:54:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiNodeEntryGetType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:55:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetTypeName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:56:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiNodeEntryGetOutputType(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:57:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetFilename(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:58:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetVersion(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:59:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiNodeEntryGetCount(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:60:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiNodeEntryGetNumParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:61:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetParameter(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam i
)
{
}

// Defined at ai_node_entry.kl:62:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryLookUpParameterAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_node_entry.kl:63:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetParamIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamIterator >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry
)
{
}

// Defined at ai_node_entry.kl:64:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryGetMetaDataIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataIterator >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::INParam nentry,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_node_entry.kl:65:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryInstall(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam type,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt8 >::INParam output_type,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeMethods >::IOParam methods,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam version
)
{
}

// Defined at ai_node_entry.kl:66:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryUninstall(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
}

// Defined at ai_node_entry.kl:72:1
FABRIC_EXT_EXPORT void _fe_AiParamIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamIterator >::IOParam iter
)
{
}

// Defined at ai_node_entry.kl:73:1
FABRIC_EXT_EXPORT void _fe_AiParamIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamIterator >::IOParam iter
)
{
}

// Defined at ai_node_entry.kl:74:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiParamIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamIterator >::INParam iter
)
{
}

// Defined at ai_node_entry.kl:80:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataIterator >::IOParam iter
)
{
}

// Defined at ai_node_entry.kl:81:1
FABRIC_EXT_EXPORT void _fe_AiMetaDataIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataIterator >::IOParam iter
)
{
}

// Defined at ai_node_entry.kl:82:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiMetaDataIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtMetaDataIterator >::INParam iter
)
{
}

// Defined at ai_nodes.kl:22:1
FABRIC_EXT_EXPORT void _fe_AiNodeAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
}

// Defined at ai_nodes.kl:23:1
FABRIC_EXT_EXPORT void _fe_AiNodeLookUpByNameAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam name
)
{
}

// Defined at ai_nodes.kl:24:1
FABRIC_EXT_EXPORT void _fe_AiNodeReset(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node
)
{
}

// Defined at ai_nodes.kl:25:1
FABRIC_EXT_EXPORT void _fe_AiNodeResetParameter(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:26:1
FABRIC_EXT_EXPORT void _fe_AiNodeClone(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:27:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node
)
{
}

// Defined at ai_nodes.kl:28:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeIs(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam str
)
{
}

// Defined at ai_nodes.kl:29:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeDeclareAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam declaration
)
{
}

// Defined at ai_nodes.kl:30:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeLink(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam src,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam input,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam target
)
{
}

// Defined at ai_nodes.kl:31:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeLinkOutput(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam src,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam output,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam target,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam input
)
{
}

// Defined at ai_nodes.kl:32:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeUnlink(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam input
)
{
}

// Defined at ai_nodes.kl:33:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeIsLinked(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam input
)
{
}

// Defined at ai_nodes.kl:34:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetLink(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam input,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::IOParam comp
)
{
}

// Defined at ai_nodes.kl:35:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:36:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetNodeEntry(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:37:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetParams(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:38:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Data _fe_AiNodeGetLocalData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:39:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetLocalData(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam data
)
{
}

// Defined at ai_nodes.kl:40:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetDisabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam disabled
)
{
}

// Defined at ai_nodes.kl:41:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeIsDisabled(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:42:1
FABRIC_EXT_EXPORT void _fe_AiNodeLookUpUserParameterAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:43:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetUserParamIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamIterator >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node
)
{
}

// Defined at ai_nodes.kl:49:1
FABRIC_EXT_EXPORT void _fe_AiUserParamIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamIterator >::IOParam iter
)
{
}

// Defined at ai_nodes.kl:50:1
FABRIC_EXT_EXPORT void _fe_AiUserParamIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamIterator >::IOParam iter
)
{
}

// Defined at ai_nodes.kl:51:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiUserParamIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtUserParamIterator >::INParam iter
)
{
}

// Defined at ai_nodes.kl:57:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetByteAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt8 >::INParam val
)
{
}

// Defined at ai_nodes.kl:58:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam val
)
{
}

// Defined at ai_nodes.kl:59:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetUIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam val
)
{
}

// Defined at ai_nodes.kl:60:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetBoolAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::INParam val
)
{
}

// Defined at ai_nodes.kl:61:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetFltAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam val
)
{
}

// Defined at ai_nodes.kl:62:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetPtrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Data >::IOParam val
)
{
}

// Defined at ai_nodes.kl:63:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetArrayAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::IOParam val
)
{
}

// Defined at ai_nodes.kl:64:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetMatrixAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::INParam val
)
{
}

// Defined at ai_nodes.kl:65:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetStrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam str
)
{
}

// Defined at ai_nodes.kl:66:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetRGBAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam r,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam g,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam b
)
{
}

// Defined at ai_nodes.kl:67:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetRGBAAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam r,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam g,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam b,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam a
)
{
}

// Defined at ai_nodes.kl:68:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetVecAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam z
)
{
}

// Defined at ai_nodes.kl:69:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetPntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam z
)
{
}

// Defined at ai_nodes.kl:70:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetPnt2AtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam x,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam y
)
{
}

// Defined at ai_nodes.kl:71:1
FABRIC_EXT_EXPORT void _fe_AiNodeSetAttributes(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::IOParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam attributes
)
{
}

// Defined at ai_nodes.kl:77:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt8 _fe_AiNodeGetByteAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:78:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiNodeGetIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:79:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 _fe_AiNodeGetUIntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:80:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeGetBoolAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:81:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Float32 _fe_AiNodeGetFltAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:82:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetRGBAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:83:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetRGBAAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec4 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:84:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetVecAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:85:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetPntAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:86:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetPnt2AtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec2 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:87:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Data _fe_AiNodeGetPtrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:88:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetArrayAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:89:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetStrAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param
)
{
}

// Defined at ai_nodes.kl:90:1
FABRIC_EXT_EXPORT void _fe_AiNodeGetMatrixAtString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::INParam node,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam param,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::INParam matrix
)
{
}

// Defined at ai_render.kl:33:1
FABRIC_EXT_EXPORT void _fe_AiBegin(
)
{
}

// Defined at ai_render.kl:34:1
FABRIC_EXT_EXPORT void _fe_AiEnd(
)
{
}

// Defined at ai_render.kl:35:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::SInt32 _fe_AiRender(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam mode
)
{
}

// Defined at ai_render.kl:36:1
FABRIC_EXT_EXPORT void _fe_AiRenderAbort(
)
{
}

// Defined at ai_render.kl:37:1
FABRIC_EXT_EXPORT void _fe_AiRenderInterrupt(
)
{
}

// Defined at ai_render.kl:38:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiRendering(
)
{
}

// Defined at ai_plugins.kl:23:1
FABRIC_EXT_EXPORT void _fe_AiLoadPlugins(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam directory
)
{
}

// Defined at ai_plugins.kl:24:1
FABRIC_EXT_EXPORT void _fe_AiLoadPlugin(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam path
)
{
}

// Defined at ai_ray.kl:93:1
FABRIC_EXT_EXPORT void _fe_AiMakeRay(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::IOParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam type,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam origin,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam dir,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam maxdist,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::INParam sg
)
{
}

// Defined at ai_ray.kl:94:1
FABRIC_EXT_EXPORT void _fe_AiReflectRay(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::IOParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam normal,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::INParam sg
)
{
}

// Defined at ai_ray.kl:95:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiRefractRay(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::IOParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::INParam normal,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam n1,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam n2,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::INParam sg
)
{
}

// Defined at ai_ray.kl:96:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTrace(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::INParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtScrSample >::IOParam sample
)
{
}

// Defined at ai_ray.kl:97:1
FABRIC_EXT_EXPORT void _fe_AiTraceBackground(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::INParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtScrSample >::IOParam sample
)
{
}

// Defined at ai_ray.kl:98:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTraceProbe(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtRay >::INParam ray,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::IOParam sgout
)
{
}

// Defined at ai_texture.kl:83:1
FABRIC_EXT_EXPORT void _fe_AiTextureParamsSetDefaults(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureParams >::IOParam params
)
{
}

// Defined at ai_texture.kl:84:1
FABRIC_EXT_EXPORT void _fe_AiTextureHandleCreate(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureHandle >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename
)
{
}

// Defined at ai_texture.kl:85:1
FABRIC_EXT_EXPORT void _fe_AiTextureHandleAccess(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec4 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::INParam sg,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureHandle >::IOParam handle,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureParams >::INParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::IOParam success
)
{
}

// Defined at ai_texture.kl:86:1
FABRIC_EXT_EXPORT void _fe_AiTextureHandleDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureHandle >::IOParam handle
)
{
}

// Defined at ai_texture.kl:87:1
FABRIC_EXT_EXPORT void _fe_AiTextureAccess(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec4 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtShaderGlobals >::INParam sg,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtTextureParams >::INParam params,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::IOParam success
)
{
}

// Defined at ai_texture.kl:88:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTextureGetResolution(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam width,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam height
)
{
}

// Defined at ai_texture.kl:89:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTextureGetNumChannels(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam num_channels
)
{
}

// Defined at ai_texture.kl:90:1
FABRIC_EXT_EXPORT void _fe_AiTextureGetChannelName(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam channel_index
)
{
}

// Defined at ai_texture.kl:91:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTextureGetFormat(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam format
)
{
}

// Defined at ai_texture.kl:92:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTextureGetBitDepth(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam bit_depth
)
{
}

// Defined at ai_texture.kl:93:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiTextureGetMatrices(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::INParam world_to_screen,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::INParam world_to_camera
)
{
}

// Defined at ai_texture.kl:94:1
FABRIC_EXT_EXPORT void _fe_AiTextureInvalidate(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam filename
)
{
}

// Defined at ai_universe.kl:32:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiUniverseIsActive(
)
{
}

// Defined at ai_universe.kl:33:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiUniverseCacheFlush(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam cache_flags
)
{
}

// Defined at ai_universe.kl:34:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetOptions(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result
)
{
}

// Defined at ai_universe.kl:35:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetCamera(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result
)
{
}

// Defined at ai_universe.kl:36:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetSceneBounds(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Box3 >::Result _result
)
{
}

// Defined at ai_universe.kl:37:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetNodeIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeIterator >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam node_mask
)
{
}

// Defined at ai_universe.kl:38:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetNodeEntryIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntryIterator >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam node_mask
)
{
}

// Defined at ai_universe.kl:39:1
FABRIC_EXT_EXPORT void _fe_AiUniverseGetAOVIterator(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtAOVIterator >::Result _result
)
{
}

// Defined at ai_universe.kl:45:1
FABRIC_EXT_EXPORT void _fe_AiNodeIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:46:1
FABRIC_EXT_EXPORT void _fe_AiNodeIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNode >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:47:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeIterator >::INParam iter
)
{
}

// Defined at ai_universe.kl:53:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntryIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:54:1
FABRIC_EXT_EXPORT void _fe_AiNodeEntryIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntryIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:55:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiNodeEntryIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtNodeEntryIterator >::INParam iter
)
{
}

// Defined at ai_universe.kl:61:1
FABRIC_EXT_EXPORT void _fe_AiAOVIteratorDestroy(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtAOVIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:62:1
FABRIC_EXT_EXPORT void _fe_AiAOVIteratorGetNext(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtAOVEntry >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtAOVIterator >::IOParam iter
)
{
}

// Defined at ai_universe.kl:63:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Boolean _fe_AiAOVIteratorFinished(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtAOVIterator >::INParam iter
)
{
}
