////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include "AtArray_functions.h"

#include "ai.h"
#include "_defines.h"

using namespace Fabric::EDK;


// Defined at GenKL\\ai_params.kl:23:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsUInt8(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt8 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsUInt8")


  #pragma message("_fe_AtArrayAsUInt8 is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsUInt8")
}

// Defined at GenKL\\ai_params.kl:24:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsUInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsUInt32")


  #pragma message("_fe_AtArrayAsUInt32 is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsUInt32")
}

// Defined at GenKL\\ai_params.kl:25:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsFloat32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsFloat32")


  #pragma message("_fe_AtArrayAsFloat32 is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsFloat32")
}

// Defined at GenKL\\ai_params.kl:26:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsVec3(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Vec3 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsVec3")


  #pragma message("_fe_AtArrayAsVec3 is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsVec3")
}

// Defined at GenKL\\ai_params.kl:27:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsMat44(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Mat44 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsMat44")


  #pragma message("_fe_AtArrayAsMat44 is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsMat44")
}

// Defined at GenKL\\ai_params.kl:28:1
FABRIC_EXT_EXPORT void _fe_AtArrayAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::String > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtArray >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtArrayAsString")


  #pragma message("_fe_AtArrayAsString is missing its implementation.")

  // Type 'AtArray' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtArrayAsString")
}
