////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
// USE COPY & PASTE TO MAKE USE OF THE FUNCTION IMPLEMENTATIONS!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha
////////////////////////////////////////////////////////////////

#include "AtParamValue_functions.h"

#include "ai.h"

using namespace Fabric::EDK;


// Defined at GenKL\\ai_params.kl:12:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt8 _fe_AtParamValueAsUInt8(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsUInt8")


  #pragma message("_fe_AtParamValueAsUInt8 is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT_RETURN("_fe_AtParamValueAsUInt8", )
}

// Defined at GenKL\\ai_params.kl:13:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::UInt32 _fe_AtParamValueAsUInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsUInt32")


  #pragma message("_fe_AtParamValueAsUInt32 is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT_RETURN("_fe_AtParamValueAsUInt32", )
}

// Defined at GenKL\\ai_params.kl:14:1
FABRIC_EXT_EXPORT Fabric::EDK::KL::Float32 _fe_AtParamValueAsFloat32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsFloat32")


  #pragma message("_fe_AtParamValueAsFloat32 is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT_RETURN("_fe_AtParamValueAsFloat32", )
}

// Defined at GenKL\\ai_params.kl:15:1
FABRIC_EXT_EXPORT void _fe_AtParamValueAsVec3(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Vec3 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsVec3")


  #pragma message("_fe_AtParamValueAsVec3 is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtParamValueAsVec3")
}

// Defined at GenKL\\ai_params.kl:16:1
FABRIC_EXT_EXPORT void _fe_AtParamValueAsMat44(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Mat44 >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsMat44")


  #pragma message("_fe_AtParamValueAsMat44 is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtParamValueAsMat44")
}

// Defined at GenKL\\ai_params.kl:17:1
FABRIC_EXT_EXPORT void _fe_AtParamValueAsString(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::AtParamValue >::INParam this_
)
{
  F2A_TRY_STATEMENT("_fe_AtParamValueAsString")


  #pragma message("_fe_AtParamValueAsString is missing its implementation.")

  // Type 'AtParamValue' could not be converted.

  F2A_CATCH_STATEMENT("_fe_AtParamValueAsString")
}
